name: pizzeria_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.1
  toggle_switch: ^0.1.8
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4
  google_fonts: ^1.1.1
  flutter_swiper: ^1.1.6


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/